### ISSUE TITLE
Problem: Captcha isn't installed? and can't make myself admin.

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/acropolis_ynh#35]
I installed acropolis 3 times, but always have the same issue: The captcha doesn't show.
I can disable captcha in the config file and create an account, but then I can't make myself an admin as `RAILS_ENV=production bundle exec rails console` prints `bundle: command not found`

https://paste.yunohost.org/raw/ruziqedaye

**Comment by weex** [comment]
Looks like it (simple_captcha) installed ok. I believe a sudo to Acropolis
is required for bundle. Will share the command in a bit.

**Comment by weex** [comment]
Ok, the highest version packaged for YunoHost (2021-12-02~ynh1) doesn't have the admin account create command. So the process once you've created an account is here: https://github.com/magicstone-dev/acropolis/issues/78#issuecomment-984956496

**Comment by ghost** [comment]
Thanks, that worked
